#   ===================================================================
#               Standard Cell Configuration File (TOML)
#   ===================================================================

#   ------------    title   -------------------------------------------

#   Start this configuration file with a good, expressive title. Something
#   like "my_lib" is common in text books, but not recommended for real
#   world designs. We recommend to name the technology you are using and
#   as postfix the target you like to hit, e.g. "lp" for low-power.

title = "LS1u_std"

#   -------------------------------------------------------------------
#                   technology
#   -------------------------------------------------------------------

#   This section describes the basic properties of the technology
#   you are using (LibreSilicon is the best, isn't it?), and the
#   parameters which determine you cell catalog.

[technology]

#   ------------    techfile    ----------------------------------------

#   Specify the path and filename of the technology file for "magic".
#   The Path can be absolute as well as relative to the local StdCellLib
#   working directory.

techfile = "./Technology/tech/LS1u.tech"

#   Note:
#   This technology should support λ-rules (lambda-rules) regarding MOSIS
#   scalable CMOS design rules. Lambda is always half the "feature size"
#   of a technology node.

#   ------------    limit   -------------------------------------------

#   Specify how many stacked transistors can be placed in one column
#   between a power supply and the (unbuffered) output. This parameter
#   is essential for the number of cells Popcorn can generate. With a
#   limit of two, the cell library contains only a couple of dozens
#   cells, while a limit of four already blows up the cell library.

limit = 4

#   ------------    buffer  -------------------------------------------

#   Specify whether cells should be buffered while reaching a
#   quantified level of stacked transistors (see limit above). The drain-
#   source-channel of every switched-on transistor increases the resistance
#   between an output and the supply rails. In other words, a output
#   high (or low) level isn't a clear high (or low) anymore when too many
#   transistors are stacked. To avoid slow switching characteristics,
#   cells with this or more stacked transistors should be buffered.

buffer = 4

#   -------------------------------------------------------------------
#                   cells
#   -------------------------------------------------------------------

#   This section specifies the properties of the cells, e.g.,
#   How high they are, on which metal the terminals are located, etc.

[cells]

#   ------------    high    -------------------------------------------

#   Specify the height of the cell layouts. This number is usually given
#   as the number of metal traces which could run horizontally above the
#   cells. E.g. if the technology file defines a metal1 as well a metal2
#   grid of 8λ, a 7-track cell becomes 7 * 8λ (= 56λ) high.

high = 11

#   ------------    terminals   ---------------------------------------

#   Specify on which physical layer the terminals (or pins) of the
#   cells are placed. Possible values are "poly", "metal1" or "metal2".
#   BTW, the occasional "poly2" layer is not common here.

terminals = "metal2"

#   Note:
#   Physical layers below the terminal layer are obviously blocked for
#   "over-the-cell" routing.

#   ------------    connectivity    -----------------------------------

#   In well-structured die layouts, different metal layers are assigned
#   different orientations. It is quite common to use metal1 for
#   horizontal wires and metal2 for vertical wires. This has impact on
#   the cell layout, while the terminals (see above) also have to be
#   easily accessible from the preferred direction. Possible values are
#   "horizontal", "vertical" as well as "unrestricted".

connectivity = "unrestricted"

#   -------------------------------------------------------------------
#                   transistors
#   -------------------------------------------------------------------

#   ------------    ratio   -------------------------------------------

#   Configure the W/L ratio between the L-size (also called gate width,
#   mostly the feature size of the technology node) and the W-size (or
#   width) of a minimum transistor. While the feature size (or 2λ)
#   depends on technology node, this ratio determines how wide the minimum
#   transistor becomes.

ratio = 1.5

#   Note:
#   A ratio of 1.5 is usually fixed by the scmos design rules (see above).
#   Wider transistores with W/L > 3/2 are faster.

#   ------------    gamma   -------------------------------------------

#   In CMOS two types of transistors are used - p-channel mosfets as well
#   as n-channel mosfets. Unfortunately, the carrier mobility in both
#   types differs - p-channel mosfets are slower. To compensate this,
#   cells usually use wider p-channel mosfets than n-channels ones. The
#   relationship between these sizes is called γ (gamma); and of course
#   depends on technology (or the doping to be more precise). Ideal
#   values are somewhere around 3, but such a value may be considered
#   impractically large; quite common is 2.

gamma = 2

#   ------------    sizing  -------------------------------------------

#   Configure the sizing strategy for the transistors. One strategy
#   could be a small footprint - all transistors inside a cell have the
#   same, minimal size. Another strategy could be a well-balanced 
#   propagation delay from all inputs to the output; a method of
#   "logical effort" is used for that strategy. Possible values for
#   sizing are "min" and "effort".

sizing = "effort"

#   ===================================================================
#               END-OF-FILE
#   ===================================================================
