#!/usr/bin/perl -w


foreach my $n(2 .. 10)
{
  open OUT,">MUX$n.cell";
  print OUT ".AUTOGENERATED by muxgen Perl Script\n";
  my @ins=();
  push @ins,"IN$_" foreach(0 .. $n-1);
  push @ins,"S$_" foreach(0 .. $n-1);
  print OUT ".inputs ".join(" ",@ins)."\n";
  print OUT ".outputs Z\n";
  print OUT ".ORDER \"MOSFET Gate Drain Source\"\n";
  foreach(0 .. $n-1)
  {
    print OUT "pmos IN$_ INT$_ vdd\n";
    print OUT "nmos IN$_ INT$_ gnd\n";
    print OUT "pmos S$_ INT$_ Y\n";
    print OUT "nmos S$_ INT$_ Y\n";
  }
  print OUT "pmos Y Z vdd\n";
  print OUT "nmos Y Z gnd\n";
  close OUT;


}
